### ISSUE TITLE
[Bug]: Undefined constant "Qruto\Flora\Console\Commands\SIGTERM"

### ISSUE THREAD

**Issue by iammursal** [qruto/laravel-flora#12]
### What happened?

After installing the package, I tried running the update cmd and I got this error.

### How to reproduce the bug

1. Install the package using 'composer require qruto/laravel-flora',  followed by 'php artisan flora:setup'
3. Run the command 'php artisan update'

### Package Version

1.0.0

### PHP Version

8.1.10

### Laravel Version

10.15.0

### Which operating systems does with happen with?

Windows

### Notes

![image](https://github.com/qruto/laravel-flora/assets/52567409/df27a7b3-b260-4f85-99de-fa241ab0b2aa)

**Comment by slavarazum** [comment]
Currently doesn't support Windows.
