### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ghena** [qruto/laravel-flora#14]
### What happened?

 composer req  qruto/laravel-flora 

Problem 1
    - Root composer.json requires qruto/laravel-flora ^1.1 -> satisfiable by qruto/laravel-flora[1.1.0].
    - qruto/laravel-flora 1.1.0 requires illuminate/bus ^10.0 -> found illuminate/bus[v10.0.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another 
require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require qruto/laravel-flora:*" to figure out if any version is installable, or "composer require qruto/laravel-flora:^2.1" if you know which you need.

### How to reproduce the bug

execute composer req

### Package Version

latest

### PHP Version

v8.1.10

### Laravel Version

9.52.15

### Which operating systems does with happen with?

Windows

**Comment by slavarazum** [comment]
Flora requires Laravel 10
